### ISSUE TITLE
 Feature Request: Remember the last bookmark

### ISSUE THREAD

**Issue by whitelujx** [MaddTheSane/Simple-Comic#90] opened 2023-01-31 14:04 UTC
Can the software add the function of remembering the position of the last open books. When I can't finish reading the book at one time, there is no bookmark function, and I can't remember the number of pages when I open it again. I have to search for half a day next time.

**Comment by nickv2002** [comment] 2023-02-02 02:00
Thanks for the request. 
This is a dupe of an earlier request. See discussion: https://github.com/MaddTheSane/Simple-Comic/issues/66#issuecomment-1413040671

**Closed as not planned by nickv2002** 2023-02-02 02:00 UTC
Labels: duplicate
