### ISSUE TITLE
backround colour not changing & and settings are not saving

### ISSUE THREAD

**Issue by ryan2004920** [MaddTheSane/Simple-Comic#106] opened 2023-09-05 22:00 UTC
when i have tried to change some of the settings such as the backround colour for when the cbr file is ful screen it is still the same colour. i have tried change the this in settings and close the application but it keeps on re setting to blue colour in settings but with the file it's still white

**Comment by nickv2002** [comment] 2023-09-05 23:39
Thanks for the report. This is a duplicate of https://github.com/MaddTheSane/Simple-Comic/issues/103
Will be fixed in next release.
(You can use an older version to pick a different color for now, see linked issue.)

**Closed as completed by nickv2002** 2023-09-05 23:39 UTC

**Comment by nickv2002** [comment] 2023-12-31 18:47
I think this is fixed in https://github.com/MaddTheSane/Simple-Comic/releases/tag/App-Store-1.9.8

LMK if otherwise in https://github.com/MaddTheSane/Simple-Comic/issues/103
