### ISSUE TITLE
Settings window takes 2 tries to appear

### ISSUE THREAD

**Issue by Scrooge78** [MaddTheSane/Simple-Comic#107] opened 2023-12-05 09:24 UTC
Hi there,
I was using Simple Comic since a couple of years with no issues, but after a while without using it, I found out that now the app is simply not loading the whole interface even if the top menu is appearing and it gives me options when clicking on the icon, opening only one CBR that was in the recent menu...
Already uninstalled, cleaned up and installed again the app...nothing changes.
Anyone experiencing the same issue?
Simple Comic Version 1.9.7 (348)
Mac OS Sonoma 14.1.1 (23B81)

**Comment by nickv2002** [comment] 2023-12-05 17:27
I haven't seen anyone with problems in Sonoma: that version of the app and OS work for me.

I'm having trouble understanding what's not working: maybe you can test a basic CBZ file and send us a screenshot?

**Comment by Scrooge78** [comment] 2023-12-05 19:16
![Uploading Screenshot 2023-12-05 alle 20.14.01.jpg…]()
Hi Nick, thanks for your feedback…
The thing is that the app is not even showing the basic interface with menu and comic viewer so is not even possible for me to send you a screenshot…it will be my empty desktop…anyway here it is attached...
![Uploading Screenshot 2023-12-05 alle 20.14.01.jpg…]()

You know, the normal view you have when you open the app, with the comics list on the left and the page viewer on the right side, nothing is appearing even the app is opened in the dock…

**Comment by DavidPhillipOster** [comment] 2023-12-05 19:33
Hi, I read the original bug report again: @Scrooge78 , you say that when you run the app you just get menu bar, and using it you can open your CBR file normally? That’s the way the app is supposed to work, just like Apple’s **Preview**: It is a viewer, so unless you tell it what to view, there is nothing for it do, except wait for you to open a file.

--- Original comment
This doesn’t fix the root cause, but should get you back up and running again:

**Simple Comic** behaves poorly if its database gets corrupted. 

This database is stored in `~/Library/Containers/com.ToWatchList.SimpleComic/Data/Library/Application Support/Simple Comic` - Note: that’s the copy  in your home directory. You can get there by opening a Finder window and typing ⌘⇧G and pasting that exact path into the text field, and hitting `return` in it are the files: `SimpleComic.sql` ,  `SimpleComic.sql-shm` , `SimpleComic.sql-wal` If, with **Simple Comic** not running, you move those files to the trash, then start **Simple Comic**, it will recreate those files.

**Comment by Scrooge78** [comment] 2023-12-11 09:37
Hi there, thanks for the feedback…
I got your point but hust to be more precise the apl itself is not even opening the settings menu…maybe also this is normal, in that case forgive me for the spam ;-)

**Comment by nickv2002** [comment] 2023-12-11 18:01
@Scrooge78 it's really difficult to understand what you are describing, but in general the settings **window** only will open if you choose it from menu bar via **Simple Comic** ➡️ **Settings**.

If you're unable to do that please send us screenshots/video of what you do see in the menu bar after attempting to launch the app.

**Comment by DavidPhillipOster** [comment] 2023-12-11 20:59
I was actually able to reproduce part of the problem:

Using Simple Comic version 1.9.7, downloaded from the apps store, on macOS Sonoma (14.1.2), on M2 Mini.

* I opened the app, closed all windows, then quit the app. That way the app will start in the no windows state.
* Open the app by clicking on the dock icon.
* Click on **Simple Comic >  Settings**,

Note the absence of a window.

* Click on **Simple Comic >  Settings** a second time.

Note that the normal Settings window appears.

* close the settings window.
* quit the app.

Now, you can repeat these steps and reliably get the same bad behavior of a missing Settings window the first time.

I was not able to reproduce the rest of the problem: Even before the first click, I could use **File > Open**

**Comment by Scrooge78** [comment] 2023-12-12 08:59
Hi there, after last message from @DavidPhillipOster , I was also able to reproduce the behavior, so I would say that no other major issues are affecting the app, cause if I click File > Open from the menu bar it works fine!
Thanks for your feedback and efforts ;-))

**Comment by nickv2002** [comment] 2023-12-18 22:06
I renamed this issue to be clearer. In Summary:

Try to bring up Settings (via menu or shortcut), first try fails, second try (and subsequent tries) work.

I'll have to check if this still happens in a new build.

**Comment by nickv2002** [comment] 2023-12-31 18:46
I think this is fixed in https://github.com/MaddTheSane/Simple-Comic/releases/tag/App-Store-1.9.8

LMK if otherwise

**Closed as completed by nickv2002** 2023-12-31 18:46 UTC
Labels: bug
