### ISSUE TITLE
background color is always white

### ISSUE THREAD

**Issue by unstoppablecarl** [MaddTheSane/Simple-Comic#105] opened 2023-08-30 17:36 UTC
The background color is always white no matter what color I set it to. 

Simple Comic Version 1.9.7 (348)
MacOs Ventura 13.2.1

**Comment by nickv2002** [comment] 2023-08-30 18:26
Thanks for the report. This is a duplicate of https://github.com/MaddTheSane/Simple-Comic/issues/103
Will be fixed in next release.

**Closed as not planned** 2023-08-30 18:27 UTC

**Comment by nickv2002** [comment] 2023-12-31 18:47
I think this is fixed in https://github.com/MaddTheSane/Simple-Comic/releases/tag/App-Store-1.9.8

LMK if otherwise in https://github.com/MaddTheSane/Simple-Comic/issues/103
